kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-smb-node-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-smb-node
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - csi-smb-node
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-smb-node
subjects:
- kind: ServiceAccount
  name: csi-smb-node-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-smb-node
  apiGroup: rbac.authorization.k8s.io

