apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-container-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - allow-privileged-containers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-container-binding
roleRef:
  kind: ClusterRole
  name: privileged-container-role
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize for the default account.
- kind: ServiceAccount
  name: default
