- name: add kernel module extras to raspberry pis
  ansible.builtin.package:
    name: linux-modules-extra-raspi
    state: present

- name: check if usb autosuspend is disabled
  lineinfile:
    backup: true
    path: /boot/firmware/cmdline.txt
    regexp: '^.*usbcore.autosuspend'
    state: absent
  check_mode: true
  register: usb_autosuspend_check
  changed_when: false

- name: disable usb autosuspend if enabled
  lineinfile:
    backrefs: true
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*)$'
    line: '\1 usbcore.autosuspend=-1'
  when: usb_autosuspend_check.found == 0


- name: bounce the machine to make sure the module is available
  ansible.builtin.reboot: