- name: add kernel module extras to raspberry pis
  ansible.builtin.package:
    name: linux-modules-extra-raspi
    state: present

- name: bounce the machine to make sure the module is available
  ansible.builtin.reboot: