apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-smb-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-smb-node
   template:
     metadata:
       labels:
         app: csi-smb-node
     spec:
       serviceAccountName: csi-smb-node-sa