---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.197/vault"
  csi.storage.k8s.io/node-stage-secret-name: "vault-smb-secrets"
  csi.storage.k8s.io/node-stage-secret-namespace: "vault"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino  # required to prevent data corruption
  - vers=3.0