apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: malwaretl-exposed
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.40-192.168.1.70
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - malwaretl-exposed