apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: csi-smb-node
spec:
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet/plugins/smb.csi.k8s.io
  - pathPrefix: /var/lib/kubelet/
  - pathPrefix: /var/lib/kubelet/plugins_registry/
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostPorts:
  - max: 29643
    min: 29643
  - max: 29645
    min: 29645
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
---