apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allowPrivilege
spec:
  privileged: true  # only allow privileged pods for this policy
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'