all:
  children:
    vm_hosts:
      hosts:
        albatross1.g-clef.net:
          ansible_user: g-clef
        albatross2.g-clefnet:
          ansible_user: g-clef
    masters:
      hosts:
        lab-cluster-master-1:
          ansible_host: 192.168.1.101
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-master-2:
          ansible_host: 192.168.1.102
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-master-6:
          ansible_host: 192.168.1.106
          ansible_user: vagrant
          ansible_become: yes
    workers:
      hosts:
        lab-cluster-worker-1:
          ansible_host: 192.168.1.111
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-worker-2:
          ansible_host: 192.168.1.112
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-worker-3:
          ansible_host: 192.168.1.113
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-worker-11:
          ansible_host: 192.168.1.121
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-worker-12:
          ansible_host: 192.168.1.122
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-worker-13:
          ansible_host: 192.168.1.123
          ansible_user: vagrant
          ansible_become: yes
        lab-cluster-worker-14:
          ansible_host: 192.168.1.124
          ansible_user: vagrant
          ansible_become: yes
    kubespray:
      children:
        masters:
        workers:
    kube_masters:
      children:
        masters:
    kube_workers:
      children:
        workers:
    kube_node:
      children:
        workers:
    k8s_cluster:
      children:
        masters:
        workers:
    etcd:
      children:
        masters:
    kube_control_plane:
      children:
        masters:
    calico_rr:
      hosts: {}
