all:
  children:
    lxd_hosts:
      # See here for how to get this working with a remote LXD. Specifically, to make this work you have to
      # have host entries for all the LXD servers, and then delegate the command to an lxc server
      # https://github.com/ansible/ansible/issues/25489
      # one *nasty* caveat to the above:
      # if you delegate VM creation to one host in a cluster, but LXD creats the VM on the other host in the cluster,
      # the ansible LXD plugin won't start it properly. So, as much as I hate this, I have to hard-code VMs to
      # particular hosts in the lxd cluster. See here:
      # https://github.com/ansible/ansible/issues/53426
      # that means also that the VM creation task has to have a 'target' entry of the LXC host we expect to create it
      # on...we need to be able to get the correct lxc "target" name from the hostname or some other hostvar of
      # the lxd host.
      hosts:
        albatross1.g-clef.net:
          ansible_user: g-clef
        albatross2.g-clef.net:
          ansible_user: g-clef
    masters:
      hosts:
        lab-cluster-master-1:
          ansible_connection: lxd
          ansible_lxd_remote: albatross2
          delegated_to: albatross2.g-clef.net
          etcd_member_name: master-1
        lab-cluster-master-2:
          ansible_connection: lxd
          ansible_lxd_remote: albatross1
          delegated_to: albatross1.g-clef.net
          etcd_member_name: master-2
        lab-cluster-master-3:
          ansible_connection: lxd
          ansible_lxd_remote: albatross2
          delegated_to: albatross2.g-clef.net
          etcd_member_name: master-3
    workers:
      hosts:
        lab-cluster-worker-1:
          ansible_connection: lxd
          ansible_lxd_remote: albatross1
          delegated_to: albatross1.g-clef.net
        lab-cluster-worker-2:
          ansible_connection: lxd
          ansible_lxd_remote: albatross2
          delegated_to: albatross2.g-clef.net
        lab-cluster-worker-3:
          ansible_connection: lxd
          ansible_lxd_remote: albatross1
          delegated_to: albatross1.g-clef.net
        lab-cluster-worker-4:
          ansible_connection: lxd
          ansible_lxd_remote: albatross2
          delegated_to: albatross2.g-clef.net
        lab-cluster-worker-5:
          ansible_connection: lxd
          ansible_lxd_remote: albatross1
          delegated_to: albatross1.g-clef.net
        lab-cluster-worker-6:
          ansible_connection: lxd
          ansible_lxd_remote: albatross2
          delegated_to: albatross2.g-clef.net
        lab-cluster-worker-7:
          ansible_connection: lxd
          ansible_lxd_remote: albatross1
          delegated_to: albatross1.g-clef.net
        lab-cluster-worker-8:
          ansible_connection: lxd
          ansible_lxd_remote: albatross2
          delegated_to: albatross2.g-clef.net
    kubespray:
      children:
        masters:
        workers:
    kube_masters:
      children:
        masters:
    kube_workers:
      children:
        workers:
    kube_node:
      children:
        workers:
    k8s_cluster:
      children:
        masters:
        workers:
    etcd:
      children:
        masters:
    kube_control_plane:
      children:
        masters:
    calico_rr:
      hosts: {}
