all:
  children:
    masters:
      hosts:
        sparrow0:
          ansible_host: 192.168.1.20
          ansible_user: ansible
          ansible_become: yes
        sparrow5:
          ansible_host: 192.168.1.25
          ansible_user: ansible
          ansible_become: yes
        # sparrow10:
        #  ansible_host: 192.168.1.30
        #  ansible_user: ansible
        #  ansible_become: yes
        sparrow15:
          ansible_host: 192.168.1.35
          ansible_user: ansible
          ansible_become: yes
    workers:
      hosts:
        sparrow1:
          ansible_host: 192.168.1.21
          ansible_user: ansible
          ansible_become: yes
        sparrow2:
          ansible_host: 192.168.1.22
          ansible_user: ansible
          ansible_become: yes
        # sparrow3:
        #  ansible_host: 192.168.1.23
        #  ansible_user: ansible
        #  ansible_become: yes
        # sparrow4:
        #  ansible_host: 192.168.1.24
        #  ansible_user: ansible
        #  ansible_become: yes
        sparrow6:
          ansible_host: 192.168.1.26
          ansible_user: ansible
          ansible_become: yes
        sparrow7:
          ansible_host: 192.168.1.27
          ansible_user: ansible
          ansible_become: yes
        sparrow8:
          ansible_host: 192.168.1.28
          ansible_user: ansible
          ansible_become: yes
        sparrow9:
          ansible_host: 192.168.1.29
          ansible_user: ansible
          ansible_become: yes
        sparrow11:
          ansible_host: 192.168.1.31
          ansible_user: ansible
          ansible_become: yes
        sparrow12:
          ansible_host: 192.168.1.32
          ansible_user: ansible
          ansible_become: yes
        #sparrow13:
        #  ansible_host: 192.168.1.33
        #  ansible_user: ansible
        #  ansible_become: yes
        sparrow14:
          ansible_host: 192.168.1.34
          ansible_user: ansible
          ansible_become: yes
        sparrow16:
          ansible_host: 192.168.1.36
          ansible_user: ansible
          ansible_become: yes
        sparrow17:
          ansible_host: 192.168.1.37
          ansible_user: ansible
          ansible_become: yes
        sparrow18:
          ansible_host: 192.168.1.38
          ansible_user: ansible
          ansible_become: yes
        sparrow19:
          ansible_host: 192.168.1.39
          ansible_user: ansible
          ansible_become: yes
    kubespray:
      children:
        masters:
        workers:
    kube_masters:
      children:
        masters:
    kube_workers:
      children:
        workers:
    kube_node:
      children:
        workers:
    k8s_cluster:
      children:
        masters:
        workers:
    etcd:
      children:
        masters:
    kube_control_plane:
      children:
        masters:
    calico_rr:
      hosts: {}
