- name: Install Worker LXC profile
  delegate_to: '{{ hostvars[inventory_hostname]["delegated_to"]}}'
  community.general.lxd_profile:
    name: '{{ hostvars[inventory_hostname]["cluster_name"] }}-worker-profile'
    description: LXC profile for workers
    state: present
    config:
      "limits.memory": '{{ hostvars[inventory_hostname]["ram_limit"]}}'
      "limits.cpu": '{{ hostvars[inventory_hostname]["cpu_limit"] }}'
      "security.privileged": "true"
      "security.nesting": "true"
      "limits.memory.swap": "false"
      "linux.kernel_modules": "overlay,nf_nat,ip_tables,ip6_tables,netlink_diag,br_netfilter,xt_conntrack,nf_nat,overlay,nf_conntrack,ip_vs"
      "raw.lxc": "lxc.apparmor.profile = unconfined\nlxc.cgroup.devices.allow = a\nlxc.mount.auto=proc:rw sys:rw\nlxc.cap.drop ="
- name: Create & start worker container
  delegate_to: '{{ hostvars[inventory_hostname]["delegated_to"]}}'
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: ubuntu/bionic/amd64
    profiles: ["default", "{{ hostvars[inventory_hostname]['cluster_name']}}-worker-profile"]
    wait_for_ipv4_addresses: true
    timeout: 600
    target: '{{ hostvars[inventory_hostname]["ansible_lxd_remote"]}}'