global:
  storageClass: postgres
  postgresql:
    auth:
      postgresPassword: <>
      database: malwarETL
      username: malwarETL
      password: <>
volumePermissions:
  enabled: true
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.40